Seed: 5177148
Traceback (most recent call last):
  File "deap_neat.py", line 262, in <module>
    main()
  File "deap_neat.py", line 247, in main
    algo.run()
  File "/home/students/cs/2017/chadji15/.local/lib/python3.8/site-packages/qdpy/algorithms/deap.py", line 217, in run
    batch, logbook = self.ea_fn(self.init_batch, self.toolbox, self.container, self.batch_size, self.niter, stats = self.stats, halloffame = self.halloffame, verbose = self.verbose, start_time = self.start_time, iteration_callback = self._iteration_callback)
  File "/home/students/cs/2017/chadji15/.local/lib/python3.8/site-packages/qdpy/algorithms/deap.py", line 76, in qdSimple
    raise ValueError("No individual could be added to the container !")
ValueError: No individual could be added to the container !
